## Assignment 2
## Team Summerhill

#### 1.	Use the same companies we picked in the Session - 2 Frontier Analysis example, and the time period 2019-2023. Risk free interest rates can be download yfinance (using the 13 week T-bill yield, symbol is ^IRX). 

In [3]:
import yfinance as yf
import pandas as pd

# Define companies and risk-free rate symbol
companies = ['AAPL','AMZN','GOOGL','BAC', 'MCD', 'CAT', 'TSLA','PFE']  # Replace with your company tickers
rf_symbol = "^IRX"
start_date = "2019-01-01"
end_date = "2023-12-31"

# Download stock data
stock_data = yf.download(companies, start=start_date, end=end_date)['Close']


combined_view = pd.concat([stock_data.head(3), stock_data.tail(3)])
print(combined_view)

[*********************100%***********************]  8 of 8 completed

Ticker            AAPL        AMZN        BAC         CAT       GOOGL  \
Date                                                                    
2019-01-02   37.708599   76.956497  21.551329  110.120667   52.543530   
2019-01-03   33.952549   75.014000  21.205956  105.877228   51.088299   
2019-01-04   35.401955   78.769501  22.086664  111.662949   53.708801   
2023-12-27  192.208359  153.339996  33.000229  293.413971  139.862976   
2023-12-28  192.636261  153.380005  33.039238  292.193573  139.723480   
2023-12-29  191.591385  151.940002  32.834450  291.002655  139.185440   

Ticker             MCD        PFE        TSLA  
Date                                           
2019-01-02  153.119019  31.940184   20.674667  
2019-01-03  152.110199  31.046598   20.024000  
2019-01-04  155.049744  31.755568   21.179333  
2023-12-27  287.580902  26.961891  261.440002  
2023-12-28  288.840393  27.131523  253.179993  
2023-12-29  289.494537  27.131523  248.479996  


In [4]:
stock_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1258 entries, 2019-01-02 to 2023-12-29
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   AAPL    1258 non-null   float64
 1   AMZN    1258 non-null   float64
 2   BAC     1258 non-null   float64
 3   CAT     1258 non-null   float64
 4   GOOGL   1258 non-null   float64
 5   MCD     1258 non-null   float64
 6   PFE     1258 non-null   float64
 7   TSLA    1258 non-null   float64
dtypes: float64(8)
memory usage: 88.5 KB


In [5]:
stock_data.isna().sum()

Ticker
AAPL     0
AMZN     0
BAC      0
CAT      0
GOOGL    0
MCD      0
PFE      0
TSLA     0
dtype: int64

In [6]:
# Download risk-free rate 
rf_data = yf.download(rf_symbol, start=start_date, end=end_date)['Close']

rf_data.tail()


[*********************100%***********************]  1 of 1 completed


Ticker,^IRX
Date,
2023-12-22,5.208
2023-12-26,5.203
2023-12-27,5.235
2023-12-28,5.218
2023-12-29,5.180


#### a.	On the first business day of January, 2024, use weekly data (before that day) to estimate the covariance matrix for weekly returns. 

In [8]:
# Download weekly stock data
stock_data = yf.download(companies, start=start_date, end=end_date, interval='1wk')['Close']
combined_view = pd.concat([stock_data.head(3), stock_data.tail(3)])
print(combined_view)

[*********************100%***********************]  8 of 8 completed

Ticker            AAPL        AMZN        BAC         CAT       GOOGL  \
Date                                                                    
2019-01-01   35.323158   81.475502  22.069397  111.732681   53.601692   
2019-01-08   35.817440   80.860497  22.768776  114.843353   52.385597   
2019-01-15   37.445930   84.809998  25.298641  119.025841   55.165024   
2023-12-12  194.934998  154.070007  32.600403  281.199890  135.309494   
2023-12-19  192.656189  153.419998  32.600403  285.776489  140.978943   
2023-12-26  191.591385  151.940002  32.834450  291.002686  139.185440   

Ticker             MCD        PFE        TSLA  
Date                                           
2019-01-01  156.736938  31.925415   22.330667  
2019-01-08  157.606659  31.290295   22.293333  
2019-01-15  158.780716  31.408463   20.150667  
2023-12-12  283.363129  25.501181  252.080002  
2023-12-19  284.798309  26.763990  252.539993  
2023-12-26  289.494537  27.131523  248.479996  


In [9]:
# Calculate weekly returns
weekly_returns = stock_data.pct_change().dropna()  # Percentage change for weekly returns

# Estimate the covariance matrix
cov_matrix_weekly = weekly_returns.cov()

# Output the covariance matrix
print("Weekly Covariance Matrix (up to January 2024):")
cov_matrix_weekly


Weekly Covariance Matrix (up to January 2024):


Ticker,AAPL,AMZN,BAC,CAT,GOOGL,MCD,PFE,TSLA
Ticker,,,,,,,,
AAPL,0.001693,0.001102,0.000840,0.000582,0.001045,0.000521,0.000520,0.001895
AMZN,0.001102,0.002142,0.000739,0.000571,0.001171,0.000370,0.000343,0.001965
BAC,0.000840,0.000739,0.002434,0.001442,0.000786,0.000744,0.000652,0.001375
CAT,0.000582,0.000571,0.001442,0.002065,0.000605,0.000641,0.000646,0.001039
GOOGL,0.001045,0.001171,0.000786,0.000605,0.001569,0.000434,0.000441,0.001582
MCD,0.000521,0.000370,0.000744,0.000641,0.000434,0.000953,0.000420,0.000863
PFE,0.000520,0.000343,0.000652,0.000646,0.000441,0.000420,0.001397,0.000569
TSLA,0.001895,0.001965,0.001375,0.001039,0.001582,0.000863,0.000569,0.008903


#### b.	Use any ML tools to forecast the returns for each stocks for the first week of January of 2024. You can use any ML models for the forecast. 

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from xgboost import XGBRegressor
# Calculate weekly returns
weekly_returns = stock_data.pct_change().dropna()

# Feature engineering - Lagged returns as features
def create_lagged_features(data, lags=3):
    df = pd.DataFrame(data)
    for lag in range(1, lags + 1):
        df[f"Lag_{lag}"] = df.iloc[:, 0].shift(lag)
    return df.dropna()

# Create lagged features for each stock
lagged_data = {}
for stock in companies:
    lagged_data[stock] = create_lagged_features(weekly_returns[stock])

# Train and predict for each stock
predictions = {}
for stock, data in lagged_data.items():
    # Define features (X) and target (y)
    X = data.iloc[:, 1:].values  # Lagged features
    y = data.iloc[:, 0].values   # Current return
    
    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # Train xgb
    model = XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=42)
    model.fit(X_train, y_train)
    
    # Predict the next week's return
    last_row = data.iloc[-1, 1:].values.reshape(1, -1)  # Use last available lagged values
    predictions[stock] = model.predict(last_row)[0]

# Output predictions
print("Forecasted Returns for the First Week of January 2024:")
for stock, pred in predictions.items():
    print(f"{stock}: {pred:.4f}")



Forecasted Returns for the First Week of January 2024:
AAPL: 0.0005
AMZN: -0.0074
GOOGL: -0.0120
BAC: 0.0052
MCD: 0.0054
CAT: 0.0113
TSLA: -0.0225
PFE: 0.0117


#### c.	Use your estimations from a) and b) to find the portfolio with the highest Sharpe ratio, i.e, the efficient frontier portfolio. You might assume that there is no short sale (portfolio coefficients are nonnegative)

In [13]:
import numpy as np
from scipy.optimize import minimize

# Forecasted returns from (b)
forecasted_returns = np.array([predictions[stock] for stock in companies])  # Replace with your actual values
forecasted_returns = np.round(forecasted_returns, 4)
forecasted_returns

array([ 0.0005, -0.0074, -0.012 ,  0.0052,  0.0054,  0.0113, -0.0225,
        0.0117], dtype=float32)

In [14]:
# Covariance matrix from (a)
cov_matrix = cov_matrix_weekly.values  # Ensure it is a NumPy array
cov_matrix=np.round(cov_matrix, 4)
cov_matrix

array([[0.0017, 0.0011, 0.0008, 0.0006, 0.001 , 0.0005, 0.0005, 0.0019],
       [0.0011, 0.0021, 0.0007, 0.0006, 0.0012, 0.0004, 0.0003, 0.002 ],
       [0.0008, 0.0007, 0.0024, 0.0014, 0.0008, 0.0007, 0.0007, 0.0014],
       [0.0006, 0.0006, 0.0014, 0.0021, 0.0006, 0.0006, 0.0006, 0.001 ],
       [0.001 , 0.0012, 0.0008, 0.0006, 0.0016, 0.0004, 0.0004, 0.0016],
       [0.0005, 0.0004, 0.0007, 0.0006, 0.0004, 0.001 , 0.0004, 0.0009],
       [0.0005, 0.0003, 0.0007, 0.0006, 0.0004, 0.0004, 0.0014, 0.0006],
       [0.0019, 0.002 , 0.0014, 0.001 , 0.0016, 0.0009, 0.0006, 0.0089]])

In [15]:
# Risk-free rate (annualized and converted to weekly)
rf_annualized = 0.05  # Example: 5% risk-free rate
rf_weekly = rf_annualized / 52

# Number of stocks
n_stocks = len(companies)

# Objective function to maximize Sharpe ratio (minimize negative Sharpe ratio)
def negative_sharpe_ratio(weights):
    portfolio_return = np.dot(weights, forecasted_returns)
    portfolio_risk = np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights)))
    sharpe_ratio = (portfolio_return - rf_weekly) / portfolio_risk
    return -sharpe_ratio  # Negative for minimization

# Constraints: weights sum to 1 and are non-negative
constraints = ({'type': 'eq', 'fun': lambda w: np.sum(w) - 1})  # Sum of weights = 1
bounds = [(0, 1) for _ in range(n_stocks)]  # No short selling

# Initial guess for weights (equal distribution)
initial_weights = np.array([1 / n_stocks] * n_stocks)

# Optimize
result = minimize(
    negative_sharpe_ratio,
    initial_weights,
    method='SLSQP',
    bounds=bounds,
    constraints=constraints
)

# Optimal portfolio weights
optimal_weights = result.x

# Calculate portfolio metrics
optimal_return = np.dot(optimal_weights, forecasted_returns)
optimal_risk = np.sqrt(np.dot(optimal_weights.T, np.dot(cov_matrix, optimal_weights)))
optimal_sharpe_ratio = (optimal_return - rf_weekly) / optimal_risk

# Output results
print("Optimal Portfolio Weights:")
for stock, weight in zip(companies, optimal_weights):
    print(f"{stock}: {weight:.4f}")

print(f"\nPortfolio Metrics:")
print(f"Expected Return: {optimal_return:.4f}")
print(f"Risk (Standard Deviation): {optimal_risk:.4f}")
print(f"Sharpe Ratio: {optimal_sharpe_ratio:.4f}")


Optimal Portfolio Weights:
AAPL: 0.0000
AMZN: 0.0000
GOOGL: 0.0000
BAC: 0.0000
MCD: 0.0063
CAT: 0.9776
TSLA: 0.0000
PFE: 0.0161

Portfolio Metrics:
Expected Return: 0.0113
Risk (Standard Deviation): 0.0315
Sharpe Ratio: 0.3273


#### d.	What is your portfolio’s actual rate of return for the first week of January 2024?  What is the rate of return for an equally weighted portfolio?

In [17]:
# Step 1: Download actual weekly data for the first week of January 2024
start_date_actual = "2024-01-01"
end_date_actual = "2024-01-09"
actual_prices = yf.download(companies, start=start_date_actual, end=end_date_actual, interval='1wk')['Close']

actual_prices


[*********************100%***********************]  8 of 8 completed


Ticker,AAPL,AMZN,BAC,CAT,GOOGL,MCD,PFE,TSLA
Date,,,,,,,,
2024-01-01,180.296707,145.240005,33.575588,284.369049,135.239746,282.152466,27.772350,237.490005
2024-01-08,184.237411,151.369995,32.795441,287.676025,140.440887,283.987976,27.706381,234.960007


In [18]:
# Step 2: Check data availability
if actual_prices.shape[0] < 2:
    print("Not enough data to calculate returns for the first week of January 2024.")
else:
    # Calculate weekly returns
    actual_returns = actual_prices.pct_change().dropna().iloc[0]  # First week's returns

    # Step 3: Calculate optimal portfolio return
    optimal_portfolio_return = np.dot(optimal_weights, actual_returns)

    # Step 4: Calculate equally weighted portfolio return
    equal_weights = np.array([1 / len(companies)] * len(companies))  # Equal weights
    equal_weighted_return = np.dot(equal_weights, actual_returns)

    # Output results
    print(f"Actual Returns for the First Week of January 2024:")
    for stock, ret in zip(companies, actual_returns):
        print(f"{stock}: {ret:.4f}")

    print(f"\nOptimal Portfolio Return: {optimal_portfolio_return:.4f}")
    print(f"Equally Weighted Portfolio Return: {equal_weighted_return:.4f}")


Actual Returns for the First Week of January 2024:
AAPL: 0.0219
AMZN: 0.0422
GOOGL: -0.0232
BAC: 0.0116
MCD: 0.0385
CAT: 0.0065
TSLA: -0.0024
PFE: -0.0107

Optimal Portfolio Return: 0.0064
Equally Weighted Portfolio Return: 0.0105


#### e.	Repeat this approach on the first business day of each week in 2024 and compute your portfolios returns. For the covariance matrix, you can update your estimation by including the newly observed prices. Your estimation of the expected returns for each stocks should also be updated.

In [20]:
import yfinance as yf
import pandas as pd
import numpy as np
from scipy.optimize import minimize
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor



# Define stock tickers and start/end dates
companies = ['AAPL', 'AMZN', 'GOOGL', 'META', 'MCD', 'GM', 'TSLA', 'PFE']
start_date = "2019-01-01"
end_date = "2024-12-31"

# Download weekly stock data
stock_data = yf.download(companies, start=start_date, end=end_date, interval='1wk')['Close']

# Define risk-free rate (fixed for simplicity here, or you can download actual values)
rf_weekly = 0.05 / 52  # Weekly risk-free rate assuming 5% annualized# Define a function to calculate the negative Sharpe ratio
def negative_sharpe_ratio(weights, forecasted_returns, cov_matrix, rf_rate):
    portfolio_return = np.dot(weights, forecasted_returns)
    portfolio_risk = np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights)))
    sharpe_ratio = (portfolio_return - rf_rate) / portfolio_risk
    return -sharpe_ratio  

# Ensure we get the first business day of each week in 2024
weekly_dates = pd.date_range(start="2024-01-01", end="2024-12-31", freq="W-MON")

# Initialize variables to track portfolio returns
weekly_portfolio_returns = []
equal_weighted_returns = []

# Iterate over each week in 2024
for current_date in weekly_dates:
    # Get historical data up to the current date
    historical_data = stock_data.loc[:current_date]
    weekly_returns = historical_data.pct_change().dropna()

    # Ensure sufficient data for covariance calculation
    if len(weekly_returns) < 2:
        print(f"Insufficient data for {current_date}. Skipping this week.")
        continue

    # Compute the covariance matrix, ensuring no invalid values
    cov_matrix = weekly_returns.cov()
    if np.any(np.isnan(cov_matrix)) or np.any(np.isinf(cov_matrix)):
        print(f"Invalid covariance matrix for {current_date}. Skipping this week.")
        continue

    # Forecast returns using lagged features and XGBoost
    forecasted_returns = []
    for stock in companies:
        data = pd.DataFrame(weekly_returns[stock])
        for lag in range(1, 4):
            data[f"Lag_{lag}"] = data[stock].shift(lag)
        data = data.dropna()
        
        if len(data) < 10:  
            forecasted_returns.append(weekly_returns[stock].mean())  
            continue

        X = data.iloc[:, 1:]  
        y = data.iloc[:, 0]  
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

        model = XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=42)
        model.fit(X_train, y_train)
        forecasted_returns.append(model.predict([X.iloc[-1]])[0])

    # Ensure forecasted returns are valid
    forecasted_returns = np.nan_to_num(forecasted_returns, nan=0.0, posinf=0.0, neginf=0.0)

    # Optimize portfolio weights
    n_stocks = len(companies)
    constraints = [{'type': 'eq', 'fun': lambda w: np.sum(w) - 1}]
    bounds = [(0, 1) for _ in range(n_stocks)]
    initial_weights = np.array([1 / n_stocks] * n_stocks)
    
    result = minimize(
        negative_sharpe_ratio,
        initial_weights,
        args=(forecasted_returns, cov_matrix, rf_weekly),
        method='SLSQP',
        bounds=bounds,
        constraints=constraints
    )
    if not result.success:
        print(f"Optimization failed for {current_date}. Skipping this week.")
        continue

    optimal_weights = result.x

    # Calculate actual returns for the current week
    next_week_data = stock_data.loc[current_date:].iloc[:2]  
    if len(next_week_data) < 2:
        print(f"Insufficient next week data for {current_date}. Skipping this week.")
        continue

    actual_weekly_returns = next_week_data.pct_change().iloc[-1].dropna()
    if len(actual_weekly_returns) != n_stocks:
        print(f"Incomplete stock data for {current_date}. Skipping this week.")
        continue

    # Adjust weights for missing data
    valid_indices = actual_weekly_returns.index.intersection(stock_data.columns)
    optimal_weights = optimal_weights[:len(valid_indices)]
    optimal_weights /= np.sum(optimal_weights) 

    # Compute portfolio returns
    actual_portfolio_return = np.dot(optimal_weights, actual_weekly_returns[valid_indices])
    weekly_portfolio_returns.append(actual_portfolio_return)

    # Compute equally weighted portfolio return
    equal_weights = np.array([1 / len(valid_indices)] * len(valid_indices))
    equal_weighted_return = np.dot(equal_weights, actual_weekly_returns[valid_indices])
    equal_weighted_returns.append(equal_weighted_return)

# Summary of Results
print("Weekly Portfolio Returns (Optimized):", weekly_portfolio_returns)
print("Weekly Portfolio Returns (Equally Weighted):", equal_weighted_returns)
print(f"Total Return (Optimized): {np.sum(weekly_portfolio_returns) * 100:.2f}%")
print(f"Total Return (Equally Weighted): {np.sum(equal_weighted_returns) * 100:.2f}%")


[*********************100%***********************]  8 of 8 completed


Insufficient next week data for 2024-12-23 00:00:00. Skipping this week.
Insufficient next week data for 2024-12-30 00:00:00. Skipping this week.
Weekly Portfolio Returns (Optimized): [-0.011530177312207176, -0.0014149693208946861, 0.05091726952868765, -0.021123468085310577, 0.030020481691010403, -0.04751565950973875, -0.00564901717973365, -0.04746143116356405, -0.0012858928144392325, 0.07270989536642423, -0.002694327435222707, 0.030172914167232306, 0.051067128343811975, -0.036975722749386764, 0.009169574279583632, 0.04618911370582481, -0.015536285380182082, 0.009943189160418668, 0.04586464016099003, -0.006707591735414804, 0.023538672229640914, -0.03305407322532636, 0.12194497119289144, 0.010206897397112155, 0.030718499393538167, 0.013946853009689338, 0.031236391166908448, 0.017182117130167384, -0.01771467156029771, 0.026596761115356127, -0.00011532476521897194, 0.05760535816537571, -0.003792735109858424, 0.004876530064561271, -0.03168936650588627, 0.008568241633768597, 0.0052445667069

#### f.	Compute the mean and standard deviation for the weekly returns of the tangent portfolio.

In [22]:
# Compute the mean and standard deviation for the weekly returns of the tangent portfolio

# Convert weekly portfolio returns to a NumPy array
weekly_portfolio_returns_np = np.array(weekly_portfolio_returns)

# Calculate the mean and standard deviation
mean_return = np.mean(weekly_portfolio_returns_np)
std_dev_return = np.std(weekly_portfolio_returns_np)

# Assuming the weekly risk-free rate (rf_weekly) is provided or can be calculated
rf_annual = 0.05  
rf_weekly = (1 + rf_annual) ** (1 / 52) - 1  

# Calculate the Sharpe ratio
sharpe_ratio = (mean_return - rf_weekly) / std_dev_return
sharpe_ratio = np.round(sharpe_ratio, 4) 

mean_return=np.round(mean_return, 4)
std_dev_return=np.round(std_dev_return, 4)
print('Mean_Weekly_return: ', mean_return)
print('Std_dev_Weekly_return: ', std_dev_return)
print('Sharpe Ratio: ', sharpe_ratio)

Mean_Weekly_return:  0.0082
Std_dev_Weekly_return:  0.0335
Sharpe Ratio:  0.2162


#### g.	Use the data from 2024, compute the mean and standard deviation of the weekly returns for the equally weighted portfolio (rebalanced at the beginning of each week).

In [24]:
# Download data for 2024
companies = ['AAPL', 'AMZN', 'GOOGL', 'META', 'MCD', 'GM', 'TSLA', 'PFE']
start_date = "2024-01-01"
end_date = "2024-12-31"
stock_data_2024 = yf.download(companies, start=start_date, end=end_date, interval='1wk')['Close']

# Calculate weekly returns
weekly_returns_2024 = stock_data_2024.pct_change().dropna()

# Compute the equally weighted portfolio returns
n_assets = len(companies)
equal_weights = np.array([1 / n_assets] * n_assets)
portfolio_returns_2024 = weekly_returns_2024.dot(equal_weights)

# Calculate mean and standard deviation of portfolio returns
mean_portfolio_return_2024 = portfolio_returns_2024.mean()
std_portfolio_return_2024 = portfolio_returns_2024.std()

# Assuming the weekly risk-free rate (rf_weekly) is provided or can be calculated
rf_annual = 0.05  
rf_weekly = (1 + rf_annual) ** (1 / 52) - 1  

# Calculate the Sharpe ratio
sharpe_ratio_2024 = (mean_portfolio_return_2024 - rf_weekly) / std_portfolio_return_2024
sharpe_ratio_2024 = np.round(sharpe_ratio_2024, 4) 

mean_portfolio_return_2024=np.round(mean_portfolio_return_2024, 4)
std_portfolio_return_2024=np.round(std_portfolio_return_2024, 4)
print('Mean_portfolio_return_2024: ', mean_portfolio_return_2024)
print('Std_portfolio_return_2024: ', std_portfolio_return_2024)
print('Sharpe Ratio: ', sharpe_ratio_2024)


[*********************100%***********************]  8 of 8 completed

Mean_portfolio_return_2024:  0.0071
Std_portfolio_return_2024:  0.0227
Sharpe Ratio:  0.2714


#### h.	Compare the results.

In [26]:
from tabulate import tabulate

# Create the comparison table as a list of lists
data = [
    ["Mean Return", 0.0082, 0.0071, "Tangent portfolio had higher returns."],
    ["Standard Deviation", 0.0335, 0.0227, "Equally weighted portfolio exhibited lower volatility."],
    ["Sharpe Ratio", 0.2162, 0.2714, "Equally weighted portfolio has better risk-adjusted return."]
]

# Define column headers
headers = ["Metric", "Tangent Portfolio (f)", "Equally Weighted Portfolio (g)", "Observations"]

# Display the table using tabulate
print(tabulate(data, headers=headers, tablefmt="grid"))


+--------------------+-------------------------+----------------------------------+-------------------------------------------------------------+
| Metric             |   Tangent Portfolio (f) |   Equally Weighted Portfolio (g) | Observations                                                |
+====================+=========================+==================================+=============================================================+
| Mean Return        |                  0.0082 |                           0.0071 | Tangent portfolio had higher returns.                       |
+--------------------+-------------------------+----------------------------------+-------------------------------------------------------------+
| Standard Deviation |                  0.0335 |                           0.0227 | Equally weighted portfolio exhibited lower volatility.      |
+--------------------+-------------------------+----------------------------------+-----------------------------------------

Observations (We use all the risk-free rate equal to 0.05):

1. Mean Return:

- The tangent portfolio has a higher mean weekly return (0.0082) compared to the equally weighted portfolio (0.0071). This indicates the tangent portfolio might be more optimal in terms of maximizing returns given the level of risk.

2. Standard Deviation (Risk):

- The standard deviation of weekly returns for the tangent portfolio (0.0335) is higher than that of the equally weighted portfolio (0.0227). This suggests that the tangent portfolio is riskier compared to the equally weighted portfolio.

3. Sharp Ratio:

- The Equally Weighted Portfolio (0.2714) is higher than the Tangent Portfolio (0.2162). This indicates the Equally Weighted Portfolio has better risk-adjusted performance.

Implications:
- The tangent portfolio provides better returns but at the cost of increased risk.
- The equally weighted portfolio offers lower risk, making it more suitable for risk-averse investors, albeit at a slightly reduced return.
- A higher Sharpe ratio suggests the portfolio is more efficient, providing more returns per unit of risk.